module.exports = [
  {
    id:1,
    url: "/images/download (16).jpg",
    name: "grainies",
    price: "230",
    category: "grocery",
  },
  {
    id:2,
    url: "/images/download.jpg",
    name: "FaceMask by tayo",
    price: "10",
    category: "facemask",
  },
  {
    id:3,
    url: "/images/download (17).jpg",
    name: "fresh dairies",
    price: "18",
    category: "grocery",
  },
  {
    id:4,
    url: "/images/download (1).jpg",
    name: "Tayo's Mask",
    price: "15.5",
    category: "facemask",
  },
  {
    id:5,
    url: "/images/download (1).jpg",
    name: "mask by air nike",
    price: "12.99",
    category: "facemask",
  },
  {
    id:6,
    url: "/images/download (5).jpg",
    name: "Spinach",
    price: "14.22",
    category: "fresh-food",
  },
  {
    id:7,
    url: "/images/download (6).jpg",
    name: "veggies",
    price: "30.17",
    category: "fresh-food",
  },
  {
    id:8,
    url: "/images/download.jpg",
    name: "full facemask",
    price: "14.50",
    category: "facemask",
  },
  {
    id:9,
    url: "/images/download (7).jpg",
    name: "eddibles",
    price: "20.21",
    category: "fresh-food",
  },
  {
    id:10,
    url: "/images/download (8).jpg",
    name: "Fruities",
    price: "40",
    category: "fresh-food",
  },
  {
    id:11,
    url: "/images/download (9).jpg",
    name: "jollof spaghetti",
    price: "17",
    category: "fresh-food",
  },
  {
    id:12,
    url: "/images/download (7).jpg",
    name: "Sphagie",
    price: "2.99",
    category: "fresh-food",
  },
  {
    id:13,
    url: "/images/download (5).jpg",
    name: "Milkos",
    price: "5",
    category: "fresh-food",
  },
  {
    id:14,
    url: "/images/download (9).jpg",
    name: "Japanese dish",
    price: "9.23",
    category: "fresh-food",
  },
  {
    id:15,
    url: "/images/download (29).jpg",
    name: "kids overall",
    price: "4",
    category: "kids",
  },
  {
    id:16,
    url: "/images/download (27).jpg",
    name: "pack of shirts",
    price: "7",
    category: "kids",
  },
  {
    id:17,
    name: "xyz line mask",
    url: "/images/download (4).jpg",
    price: "25",
    category: "facemask",
  },
  {
    id:18,
    url: "/images/download (6).jpg",
    name: "French fries",
    price: "11.17",
    category: "fresh-food",
  },
  {
    id:19,
    url: "/images/download (10).jpg",
    name: "chopsticks",
    price: "50",
    category: "fresh-food",
  },
  {
    id:20,
    url: "/images/download (11).jpg",
    name: "protein box",
    price: "9.50",
    category: "grocery",
  },
  {
    id:21,
    url: "/images/download (12).jpg",
    name: "sunlight pack",
    price: "23.70",
    category: "grocery",
  },
  {
    id:22,
    url: "/images/download (26).jpg",
    name: "kids party dress",
    price: "26",
    category: "kids",
  },
  {
    id:23,
    url: "/images/download (27).jpg",
    name: "infant wears",
    price: "23",
    category: "kids",
  },
  {
    id:24,
    url: "/images/download (18).jpg",
    name: "modern round sofa",
    price: "290",
    category: "home",
  },
  {
    id:25,
    url: "/images/download (13).jpg",
    name: "support growers",
    price: "99.20",
    category: "grocery",
  },
  {
    id:26,
    url: "/images/download (18).jpg",
    name: "dream round sofa",
    price: "600",
    category: "home",
  },
  {
    id:27,
    url: "/images/download (19).jpg",
    name: "kitchen shelf",
    price: "120",
    category: "home",
  },
  {
    id:28,
    url: "/images/download (2).jpg",
    name: "FaceMask by Jodan",
    price: "19.99",
    category: "facemask",
  },
  {
    id:29,
    url: "/images/download (3).jpg",
    name: "FaceMask by Titi",
    price: "5.99",
    category: "facemask",
  },
  {
    id:30,
    url: "/images/download (21).jpg",
    name: "wine shelf",
    price: "90",
    category: "home",
  },
  {
    id:31,
    url: "/images/download (20).jpg",
    name: "modern sofa",
    price: "",
    category: "home",
  },
  {
    id:32,
    url: "/images/download (22).jpg",
    name: "modern book shelf",
    price: "68",
    category: "home",
  },
  {
    id:33,
    url: "/images/download (3).jpg",
    name: "justin's facemask",
    price: "20",
    category: "facemask",
  },
  {
    id:34,
    url: "/images/download (23).jpg",
    name: "work space table",
    price: "86.99",
    category: "home",
  },
  {
    id:35,
    url: "/images/download (24).jpg",
    name: "dream furniture bed",
    price: "2050.99",
    category: "home",
  },
  {
    id:36,
    url: "/images/download (25).jpg",
    name: "kids play room",
    price: "12000",
    category: "home",
  },
  {
    id:37,
    url: "/images/download (25).jpg",
    name: "3d shelves",
    price: "390",
    category: "home",
  },
  {
    id:38,
    url: "/images/download (4).jpg",
    name: "Reusable Mask",
    price: "50",
    category: "facemask",
  },
  {
    id:39,
    url: "/images/download (2).jpg",
    name: "random mask",
    price: "30.99",
    category: "facemask",
  },
  {
    id:40,
    url: "/images/download (23).jpg",
    name: "modern drawer",
    price: "126",
    category: "home",
  },
  {
    id:41,
    url: "/images/download (26).jpg",
    name: "nike kiddies",
    price: "15",
    category: "kids",
  },
  {
    id:42,
    url: "/images/download (28).jpg",
    name: "hoddies",
    price: "12.99",
    category: "kids",
  },
  {
    id:43,
    url: "/images/download (30).jpg",
    name: "cool kid shirt",
    price: "10.99",
    category: "kids",
  },
  {
    id:44,
    url: "/images/download (14).jpg",
    name: "island mart",
    price: "1200.60",
    category: "grocery",
  },
  {
    id:45,
    url: "/images/download (15).jpg",
    name: "fruit shop",
    price: "111",
    category: "grocery",
  },
  {
    id:46,
    url: "/images/download (26).jpg",
    name: "cool kids dress",
    price: "20",
    category: "kids",
  },
];
